### ISSUE TITLE
[splashscreen, looknfeel, window deco kcm]: selection marker _jumps_ through all entries before "landing on the current selected entry"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.10#33] opened 2016-10-22 10:00 UTC
places seen this:
wallpaper dialog, desktop theme kcm, lookandfeel theme

**Comment by notmart** [comment] 2016-11-25 15:27
If i understood correctly, the issue is that in those kcms the selected item looks like it's the first for a moment, then the proper one gets selected afterwards, sometimes causing scroll of the view, right?

**Comment by star-buck** [comment] 2016-11-25 15:30
Right, mostly doing a "wheel of fortune" spinning the marker forward until it lands on the active one.

**Comment by notmart** [comment] 2016-11-25 16:58
I think i found out where the issue lies. I still have to do some tests for a couple of possible fixes, but should be fixable without any graphics glitch left

**Comment by notmart** [comment] 2016-11-29 14:45
Tentative fixes landed and ready to be tested
fix for l&f kcm: https://cgit.kde.org/plasma-desktop.git/commit/?id=ee2ec66a415580a5c4ccfdb34e5f6e68a7739652
plasma theme kcm: https://commits.kde.org/plasma-desktop/d9d52a37c6ba267f7da936c0436b254788f7cb87
wallpaper: https://commits.kde.org/plasma-workspace/5434e4bc014181841df0e24979e03288584b8696
(latter one should solve https://github.com/blue-systems/plasma-5.8/issues/32 as well)

**Comment by star-buck** [comment] 2017-01-12 21:25
still jumps on:
- splash screen kcm
-

**Comment by star-buck** [comment] 2017-01-12 21:30
also window deco still jumps

**Comment by star-buck** [comment] 2017-02-03 16:53
tested on neon5.9 and still those two kcm selection markers "jump"

**Comment by notmart** [comment] 2017-02-21 10:09
splash screen kcm fixed on master

**Comment by notmart** [comment] 2017-02-21 12:03
for kwin https://phabricator.kde.org/D4703

**Comment by notmart** [comment] 2017-02-24 15:01
fixes laded, should be testable on devel edition

**Closed** 2017-05-19 16:23 UTC
Labels: ready for QA
